server:
  port: 8080
  servlet:
    context-path: /dio


spring:
  datasource:
    platform: postgres
    url: postgres://xmkcosylnfbzeb:e921470ff81abc32b7be3114f45155929c12b2f4e9113a5c3a37dfa67233b951@ec2-54-157-100-65.compute-1.amazonaws.com:5432/d84nkd2c79p9ep
    username: xmkcosylnfbzeb
    password: e921470ff81abc32b7be3114f45155929c12b2f4e9113a5c3a37dfa67233b951
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Bootcamp DIO - Santander